### ISSUE TITLE
Support feature flags API

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/posthog-php#10]
Via the PHP library, I would like to be able to use the `decide` endpoint to check the status of a feature for a user

**Comment by joesaunderson** [comment]
I noticed this PR from a fork: https://github.com/zidsa/posthog-php/pull/1

Is this something that could be merged to the upstream (it looks like it also does PSR-4 at the same time).

**Comment by mariusandra** [comment]
Hey @zidsa, would you be willing to contribute your feature flags code upstream to through a PR? :)

**Comment by yakkomajuri** [comment]
🎉
