### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wppd** [PostHog/posthog-php#2]
1, should handle 'host' (https://www.test.com) and 'use_ssl' => true, it becomes `https://https://www.test.com`
2, LibCurl the batch api endpoint is 'capture' rather than 'batch'
3, the endless loop when http code is 0

**Comment by mariusandra** [comment]
Hi @wppd ! Thank you for reporting these issues!
1. Done. Now if you specify `host` with either `http://` or `https://`, it'll automatically set the `ssl` parameter.
2. I couldn't replicate this. It looks like [`/batch/`](https://github.com/PostHog/posthog-php/blob/master/lib/PostHog/Consumer/LibCurl.php#L55) to me...?
3. The code `0` will now be treated as a regular error. No more endless loop!

**Comment by wppd** [comment]
oh I was going to squeeze some time to contribute.... 2 I will test it again
