### ISSUE TITLE
Slowness in Posthog server response, cause general slowness

### ISSUE THREAD

**Issue by allan-simon** [PostHog/posthog-php#32]
We're using a self-hosted instance of posthog, for some events we record them on server side using this library.

We experienced recently a general slowness of the application for some endpoints.

After investigation the slowness was correlated to our posthog instance having performance issue (most precisely it was timeout-ing due to  a disk full, so the client was waiting for the connection to timeout,  so each requests were having a +10s hit). 

The question is, is there a way to  avoid that ? (i.e the same as on client side, the call being non-blocking, the fact they timeout or fail does not affect the business code)

**Comment by yakkomajuri** [comment]
Hey @allan-simon! I'll make the default more sensible, but the timeout is configurable! See this comment for details:

https://github.com/PostHog/posthog-php/pull/24#issue-1016030892

**Comment by yakkomajuri** [comment]
Done! New default is 750ms, please upgrade to 2.1.1.

Thanks for raising this
