### ISSUE TITLE
FeatureFlags: PHP issues a warning for non-local feature flags that are not enabled for the user

### ISSUE THREAD

**Issue by tamc** [PostHog/posthog-php#48]
In PHP. 

If: 
1. you have defined a feature flag and
2. it is not locally computable and 
3. it not enabled for the user you are checking 

(Or, a rarer case, you are checking for an undefined feature flag)

Then PHP will throw a warning of the form 
`PHP Warning:  Undefined array key "<feature flag name>" in /var/www/vendor/posthog/posthog-php/lib/Client.php on line 234`

This can generate a lot of log spam if a feature flag is only enabled for a small % of users.

We could suppress that kind of warning in our PHP config, but it is helpful to have it exist to highlight cases where the key should have been defined.

The fix is easy, and shown in this (unfortunately outdated) PR: https://github.com/PostHog/posthog-php/pull/42

I can update the PR, but before I do, was there a reason it was not merged? Is this in some way expected behaviour?

**Comment by edhgoose** [comment]
We've just upgraded our library and having the same experience. We track each warning in Sentry, so we're getting constant alerts from Sentry about unexpected behaviour.

**Comment by neilkakkar** [comment]
This is fixed now :)
